name: PR Comment
on:
  issue_comment:
    types: [created]

jobs:
  test_job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - env:
          DATA: ${{ toJSON(github) }}
        run: |
          echo $DATA
  hello_world:
    name: Say Hello
    runs-on: ubuntu-latest
    if: (github.event.comment.body == "Hello World!") && (github.event.comment.user.type == "User")
    steps:
      - env:
          COMMENT_URL: ${{ github.event.comment.issue_url }}
          USER: ${{ github.event.comment.user.login }}
        run: |
          curl
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"body\": \"@$USER\"}" \
            -X POST "$COMMENT_URL/comments"
