name: PR Comment
on:
  issue_comment:
    types: [created]

jobs:
  test_job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - env:
          DATA: ${{ toJSON(github) }}
        run: |
          echo $DATA
